[package]
name = "dee-bugee-rust"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
crossbeam-channel.workspace = true
dee-bugee-schema = { path = "../toolkit-schema" }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["registry"] }
