[package]
name = "debug-logging-toolkit-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
debug-logging-toolkit-schema = { path = "../toolkit-schema" }
roaring.workspace = true
serde.workspace = true
serde_json.workspace = true
