[package]
name = "dee-bugee"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
crossbeam-channel.workspace = true
dee-bugee-core = { path = "../toolkit-core" }
dee-bugee-schema = { path = "../toolkit-schema" }
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
rfd.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Threading"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
